# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import createnotification_pb2 as createnotification__pb2


class CreateNotificationStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.create_notification = channel.unary_unary(
        '/CreateNotification/create_notification',
        request_serializer=createnotification__pb2.RequestData.SerializeToString,
        response_deserializer=createnotification__pb2.ResponseData.FromString,
        )


class CreateNotificationServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def create_notification(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CreateNotificationServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'create_notification': grpc.unary_unary_rpc_method_handler(
          servicer.create_notification,
          request_deserializer=createnotification__pb2.RequestData.FromString,
          response_serializer=createnotification__pb2.ResponseData.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'CreateNotification', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
