# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: createnotification.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='createnotification.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x18\x63reatenotification.proto\"\xa5\x01\n\x0bRequestData\x12\x10\n\x08template\x18\x01 \x01(\t\x12\x17\n\x0fmicroservice_id\x18\x02 \x01(\x05\x12\x0f\n\x07user_id\x18\x03 \x01(\x05\x12*\n\x07\x63ontent\x18\x04 \x03(\x0b\x32\x19.RequestData.ContentEntry\x1a.\n\x0c\x43ontentEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"8\n\x0cResponseData\x12\x14\n\x0csuccessfully\x18\x01 \x01(\t\x12\x12\n\nmessage_id\x18\x02 \x01(\t2J\n\x12\x43reateNotification\x12\x34\n\x13\x63reate_notification\x12\x0c.RequestData\x1a\r.ResponseData\"\x00\x62\x06proto3'
)




_REQUESTDATA_CONTENTENTRY = _descriptor.Descriptor(
  name='ContentEntry',
  full_name='RequestData.ContentEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='RequestData.ContentEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='RequestData.ContentEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=148,
  serialized_end=194,
)

_REQUESTDATA = _descriptor.Descriptor(
  name='RequestData',
  full_name='RequestData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='template', full_name='RequestData.template', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='microservice_id', full_name='RequestData.microservice_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='RequestData.user_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content', full_name='RequestData.content', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_REQUESTDATA_CONTENTENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=194,
)


_RESPONSEDATA = _descriptor.Descriptor(
  name='ResponseData',
  full_name='ResponseData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='successfully', full_name='ResponseData.successfully', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message_id', full_name='ResponseData.message_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=196,
  serialized_end=252,
)

_REQUESTDATA_CONTENTENTRY.containing_type = _REQUESTDATA
_REQUESTDATA.fields_by_name['content'].message_type = _REQUESTDATA_CONTENTENTRY
DESCRIPTOR.message_types_by_name['RequestData'] = _REQUESTDATA
DESCRIPTOR.message_types_by_name['ResponseData'] = _RESPONSEDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RequestData = _reflection.GeneratedProtocolMessageType('RequestData', (_message.Message,), {

  'ContentEntry' : _reflection.GeneratedProtocolMessageType('ContentEntry', (_message.Message,), {
    'DESCRIPTOR' : _REQUESTDATA_CONTENTENTRY,
    '__module__' : 'createnotification_pb2'
    # @@protoc_insertion_point(class_scope:RequestData.ContentEntry)
    })
  ,
  'DESCRIPTOR' : _REQUESTDATA,
  '__module__' : 'createnotification_pb2'
  # @@protoc_insertion_point(class_scope:RequestData)
  })
_sym_db.RegisterMessage(RequestData)
_sym_db.RegisterMessage(RequestData.ContentEntry)

ResponseData = _reflection.GeneratedProtocolMessageType('ResponseData', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSEDATA,
  '__module__' : 'createnotification_pb2'
  # @@protoc_insertion_point(class_scope:ResponseData)
  })
_sym_db.RegisterMessage(ResponseData)


_REQUESTDATA_CONTENTENTRY._options = None

_CREATENOTIFICATION = _descriptor.ServiceDescriptor(
  name='CreateNotification',
  full_name='CreateNotification',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=254,
  serialized_end=328,
  methods=[
  _descriptor.MethodDescriptor(
    name='create_notification',
    full_name='CreateNotification.create_notification',
    index=0,
    containing_service=None,
    input_type=_REQUESTDATA,
    output_type=_RESPONSEDATA,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CREATENOTIFICATION)

DESCRIPTOR.services_by_name['CreateNotification'] = _CREATENOTIFICATION

# @@protoc_insertion_point(module_scope)
